--- Attacker Assumptions
--- 1. keep learning
--- 2. know public keys and certificates
--- 3. have its own private key and certificate
fmod MAN-IN-THE-MIDDLE-ACTION is
  protecting CONTENT-TYPE .
  protecting HANDSHAKE-TYPE .
  protecting TLS-CONTENT-ID .
  protecting TLS-COMPONENT-ID .
  protecting TLS-MESSAGE-VALUE .
  protecting TLS-MESSAGE-CHANGE-OPERATION .

  sorts MITMAction MITMActionItem .
  subsort MITMActionItem < MITMAction .
  op none : -> MITMAction [ctor] .
  op _|_ : MITMAction MITMAction -> MITMAction [ctor assoc id: none] .

  --- Message flow modification
  op skip : HandshakeType -> MITMActionItem [ctor] .
  op skip(*) : -> MITMActionItem [ctor] . 
  op duplicate : HandshakeType -> MITMActionItem [ctor] .
  op duplicate(*) : -> MITMActionItem [ctor] . 


  --- Intermediate message generation and impersonation
  op buildMessage : HandshakeType TId -> MITMActionItem [ctor] .
  op buildMessage : ContentType TId -> MITMActionItem [ctor] .

  --- encrypt/decrypt messages
  ops encrypt decrypt : -> MITMActionItem [ctor] .

  op attackContent : TLSContentId ChangeOperation -> MITMActionItem .
endfm

smod MAN-IN-THE-MIDDLE-ACTION-STRATEGY is
  --- protecting MAN-IN-THE-MIDDLE-ACTION .
  --- protecting ATTACKER-BEHAVIOR .

  --- var MITM : MITMAction .
  --- vars PV PV' : ProtocolVersion .
  --- vars CS CS' : CipherSuite .
  --- vars CM CM' : CompressionMethod .
  --- var HTY : HandshakeType .
  --- vars SHALGO SHALGO' : SignatureAndHashAlgorithm .
  --- vars CERT CERT' : Certificate .

  --- strat attack : MITMAction @ ConfWithAction .

  --- sd attack(skip(*) | MITM) := skip | attack(MITM) .
  --- sd attack(skip(HTY) | MITM) := skipHandshake[HTY <- HTY] | attack(MITM) .

  --- sd attack(duplicate(*) | MITM) := duplicate | attack(MITM) .
  --- sd attack(duplicate(HTY) | MITM) := duplicateHandshake[HTY <- HTY] | attack(MITM) .

  --- sd attack(attackContent(client-version, replace(v[PV], v[PV'])) | MITM) := changeProtocolVersion[HTY <- client-hello, PV <- PV, PV' <- PV'] | attack(MITM) . 
  --- sd attack(attackContent(client-version, replace(*, v[PV'])) | MITM) := changeProtocolVersion[HTY <- client-hello, PV' <- PV'] | attack(MITM) . 
  --- sd attack(attackContent(client-version, replace(v[PV], *)) | MITM) := changeProtocolVersion[HTY <- client-hello, PV <- PV] | attack(MITM) . 
  --- sd attack(attackContent(client-version, replace(*, *)) | MITM) := changeProtocolVersion[HTY <- client-hello] | attack(MITM) . 

  --- sd attack(attackContent(server-version, replace(v[PV], v[PV'])) | MITM) := changeProtocolVersion[HTY <- server-hello, PV <- PV, PV' <- PV'] | attack(MITM) . 
  --- sd attack(attackContent(server-version, replace(*, v[PV'])) | MITM) := changeProtocolVersion[HTY <- server-hello, PV' <- PV'] | attack(MITM) . 
  --- sd attack(attackContent(server-version, replace(v[PV], *)) | MITM) := changeProtocolVersion[HTY <- server-hello, PV <- PV] | attack(MITM) . 
  --- sd attack(attackContent(server-version, replace(*, *)) | MITM) := changeProtocolVersion[HTY <- server-hello] | attack(MITM) . 

  --- sd attack(attackContent(cipher-suites, add(v[CS])) | MITM) := changeCipherSuite1[CS <- CS] | attack(MITM) .
  --- sd attack(attackContent(cipher-suites, add(*)) | MITM) := changeCipherSuite1 | attack(MITM) .
  --- sd attack(attackContent(cipher-suites, delete(v[CS])) | MITM) := changeCipherSuite2[CS <- CS] | attack(MITM) .
  --- sd attack(attackContent(cipher-suites, delete(*)) | MITM) := changeCipherSuite2 | attack(MITM) .
  --- sd attack(attackContent(cipher-suites, replace(v[CS], v[CS'])) | MITM) := changeCipherSuite3[HTY <- client-hello, CS <- CS, CS' <- CS'] | attack(MITM) .
  --- sd attack(attackContent(cipher-suites, replace(*, v[CS'])) | MITM) := changeCipherSuite3[HTY <- client-hello, CS' <- CS'] | attack(MITM) .
  --- sd attack(attackContent(cipher-suites, replace(v[CS], *)) | MITM) := changeCipherSuite3[HTY <- client-hello, CS <- CS] | attack(MITM) .
  --- sd attack(attackContent(cipher-suites, replace(*, *)) | MITM) := changeCipherSuite3[HTY <- client-hello] | attack(MITM) .
  --- 
  --- sd attack(attackContent(cipher-suite, replace(v[CS], v[CS'])) | MITM) := changeCipherSuite3[HTY <- server-hello, CS <- CS, CS' <- CS'] | attack(MITM) .
  --- sd attack(attackContent(cipher-suite, replace(*, v[CS'])) | MITM) := changeCipherSuite3[HTY <- server-hello, CS' <- CS'] | attack(MITM) .
  --- sd attack(attackContent(cipher-suite, replace(v[CS], *)) | MITM) := changeCipherSuite3[HTY <- server-hello, CS <- CS] | attack(MITM) .
  --- sd attack(attackContent(cipher-suite, replace(*, *)) | MITM) := changeCipherSuite3[HTY <- server-hello] | attack(MITM) .

  --- sd attack(attackContent(client-random, replace(*, *)) | MITM) := changeRandom[HTY <- client-hello] | attack(MITM) .
  --- sd attack(attackContent(server-random, replace(*, *)) | MITM) := changeRandom[HTY <- server-hello] | attack(MITM) .

  --- sd attack(attackContent(client-session-id, replace(*, *)) | MITM) := changeSessionId[HTY <- client-hello] | attack(MITM) .
  --- sd attack(attackContent(server-session-id, replace(*, *)) | MITM) := changeSessionId[HTY <- server-hello] | attack(MITM) .

  --- sd attack(attackContent(compression-methods, add(v[CM])) | MITM) := changeCompressionMethod1[CM <- CM] | attack(MITM) .
  --- sd attack(attackContent(compression-methods, add(*)) | MITM) := changeCompressionMethod1 | attack(MITM) .
  --- sd attack(attackContent(compression-methods, delete(v[CM])) | MITM) := changeCompressionMethod2[CM <- CM] | attack(MITM) .
  --- sd attack(attackContent(compression-methods, delete(*)) | MITM) := changeCompressionMethod2 | attack(MITM) .
  --- sd attack(attackContent(compression-methods, replace(v[CM], v[CM'])) | MITM) := changeCompressionMethod3[HTY <- client-hello, CM <- CM, CM' <- CM'] | attack(MITM) .
  --- sd attack(attackContent(compression-methods, replace(*, v[CM'])) | MITM) := changeCompressionMethod3[HTY <- client-hello, CM' <- CM'] | attack(MITM) .
  --- sd attack(attackContent(compression-methods, replace(v[CM], *)) | MITM) := changeCompressionMethod3[HTY <- client-hello, CM <- CM] | attack(MITM) .
  --- sd attack(attackContent(compression-methods, replace(*, *)) | MITM) := changeCompressionMethod3[HTY <- client-hello] | attack(MITM) .

  --- sd attack(attackContent(compression-method, replace(v[CM], v[CM'])) | MITM) := changeCompressionMethod3[HTY <- server-hello, CM <- CM, CM' <- CM'] | attack(MITM) .
  --- sd attack(attackContent(compression-method, replace(*, v[CM'])) | MITM) := changeCompressionMethod3[HTY <- server-hello, CM' <- CM'] | attack(MITM) .
  --- sd attack(attackContent(compression-method, replace(v[CM], *)) | MITM) := changeCompressionMethod3[HTY <- server-hello, CM <- CM] | attack(MITM) .
  --- sd attack(attackContent(compression-method, replace(*, *)) | MITM) := changeCompressionMethod3[HTY <- server-hello] | attack(MITM) .

  --- sd attack(attackContent(supported-signature-algorithms, add(v[SHALGO])) | MITM) := changeSupportedSignatureAlgorithms1[SHALGO <- SHALGO] | attack(MITM) .
  --- sd attack(attackContent(supported-signature-algorithms, add(*)) | MITM) := changeSupportedSignatureAlgorithms1 | attack(MITM) .
  --- sd attack(attackContent(supported-signature-algorithms, delete(v[SHALGO])) | MITM) := changeSupportedSignatureAlgorithms2[SHALGO <- SHALGO] | attack(MITM) .
  --- sd attack(attackContent(supported-signature-algorithms, delete(*)) | MITM) := changeSupportedSignatureAlgorithms2 | attack(MITM) .
  --- sd attack(attackContent(supported-signature-algorithms, replace(v[SHALGO], v[SHALGO'])) | MITM) := changeSupportedSignatureAlgorithms3[SHALGO <- SHALGO, SHALGO' <- SHALGO'] | attack(MITM) .
  --- sd attack(attackContent(supported-signature-algorithms, replace(*, v[SHALGO'])) | MITM) := changeSupportedSignatureAlgorithms3[SHALGO' <- SHALGO'] | attack(MITM) .
  --- sd attack(attackContent(supported-signature-algorithms, replace(v[SHALGO], *)) | MITM) := changeSupportedSignatureAlgorithms3[SHALGO <- SHALGO] | attack(MITM) .
  --- sd attack(attackContent(supported-signature-algorithms, replace(*, *)) | MITM) := changeSupportedSignatureAlgorithms3 | attack(MITM) .

  --- sd attack(attackContent(certificate-list, add(v[CERT])) | MITM) := changeCertificateList1[CERT <- CERT] | attack(MITM) .
  --- sd attack(attackContent(certificate-list, add(*)) | MITM) := changeCertificateList1 | attack(MITM) .
  --- sd attack(attackContent(certificate-list, delete(v[CERT])) | MITM) := changeCertificateList2[CERT <- CERT] | attack(MITM) .
  --- sd attack(attackContent(certificate-list, delete(*)) | MITM) := changeCertificateList2 | attack(MITM) .
  --- sd attack(attackContent(certificate-list, replace(v[CERT], v[CERT'])) | MITM) := changeCertificateList3[CERT <- CERT, CERT' <- CERT'] | attack(MITM) .
  --- sd attack(attackContent(certificate-list, replace(*, v[CERT'])) | MITM) := changeCertificateList3[CERT' <- CERT'] | attack(MITM) .
  --- sd attack(attackContent(certificate-list, replace(v[CERT], *)) | MITM) := changeCertificateList3[CERT <- CERT] | attack(MITM) .
  --- sd attack(attackContent(certificate-list, replace(*, *)) | MITM) := changeCertificateList3 | attack(MITM) .
  --- --- extensions ...
  --- sd attack(none) := fail .
endsm
