#!/usr/bin/env python3
"""Generate RQ5 aggregate BehaviorDVSpec sets from RFC scenario files."""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path


RQ5_DIR = Path(__file__).resolve().parents[1]
SCENARIO_DIR = RQ5_DIR.parent
RFC_DIR = SCENARIO_DIR / "rfc"
OUT_FILE = RQ5_DIR / "all-behavior-deviation.maude"


@dataclass(frozen=True)
class Source:
    name: str
    path: Path


@dataclass(frozen=True)
class SpecBlock:
    source: str
    index: int
    body: str
    tuple_count: int


GROUPS = (
    (
        "allBehaviorDeviationSetV2",
        (Source("5246-core", RFC_DIR / "5246-core.maude"),),
    ),
    (
        "allBehaviorDeviationSetV3",
        (
            Source("8446-core", RFC_DIR / "8446-core.maude"),
            Source("hrr", RFC_DIR / "hrr.maude"),
            Source("psk", RFC_DIR / "psk.maude"),
        ),
    ),
)


EQ_RE = re.compile(r"^\s*eq\s+behaviorDeviationSpecification(\d+)\s*=")
LABEL_RE = re.compile(r"\{'[^,\s]+")


def strip_equation_dot(line: str) -> str:
    return re.sub(r"\s*\.\s*$", "", line.rstrip())


def extract_spec_blocks(source: Source, aggregate_label: str) -> list[SpecBlock]:
    lines = source.path.read_text(encoding="utf-8").splitlines()
    blocks: list[SpecBlock] = []
    i = 0

    while i < len(lines):
        line = lines[i]
        match = EQ_RE.match(line)
        if not match:
            i += 1
            continue

        index = int(match.group(1))
        eq_lines: list[str] = []
        rest = line.split("=", 1)[1].strip()
        if rest:
            eq_lines.append(rest)

        while not line.strip().endswith("."):
            i += 1
            if i >= len(lines):
                raise ValueError(f"unterminated behaviorDeviationSpecification{index} in {source.path}")
            line = lines[i]
            eq_lines.append(line.rstrip())

        if eq_lines:
            eq_lines[-1] = strip_equation_dot(eq_lines[-1])

        body = "\n".join(eq_lines).strip()
        if body == "empty":
            i += 1
            continue

        body = LABEL_RE.sub("{'" + aggregate_label, body)
        tuple_count = len(LABEL_RE.findall(body))
        blocks.append(SpecBlock(source.name, index, body, tuple_count))
        i += 1

    return blocks


def indent_body(body: str) -> str:
    return "\n".join(("     " + line.lstrip()) if line.strip() else "" for line in body.splitlines())


def render_group(op_name: str, sources: tuple[Source, ...]) -> tuple[str, int, int]:
    blocks: list[SpecBlock] = []
    for source in sources:
        blocks.extend(extract_spec_blocks(source, op_name))

    out: list[str] = []
    tuple_count = sum(block.tuple_count for block in blocks)
    out.append(f"  --- sources: {' '.join(source.name for source in sources)}")
    out.append(f"  --- non-empty behaviorDeviationSpecification blocks: {len(blocks)}")
    out.append(f"  --- BehaviorDVSpec entries before Set duplicate elimination: {tuple_count}")
    out.append(f"  op {op_name} : -> Set{{BehaviorDVSpec}} .")

    if not blocks:
        out.append(f"  eq {op_name} = empty .")
        return "\n".join(out), 0, 0

    out.append(f"  eq {op_name} =")
    for pos, block in enumerate(blocks):
        out.append(f"     --- {block.source}: behaviorDeviationSpecification{block.index}")
        body = indent_body(block.body)
        if pos + 1 < len(blocks):
            body += ","
        else:
            body += " ."
        out.append(body)
    return "\n".join(out), len(blocks), tuple_count


def main() -> None:
    rendered: list[str] = [
        "--- Generated by scripts/generate_aggregate.py; do not edit by hand.",
        "load ../../requirements/mixed-base.maude",
        "load ../threat-module.maude",
        "",
        "smod RQ5-ALL-BEHAVIOR-DEVIATION is",
        "  protecting RUN-SCENARIO .",
        "  protecting SET{BehaviorDVSpec} .",
        "",
    ]

    summaries: list[str] = []
    for index, (op_name, sources) in enumerate(GROUPS):
        group_text, block_count, tuple_count = render_group(op_name, sources)
        if index:
            rendered.append("")
        rendered.append(group_text)
        summaries.append(f"{op_name}: {block_count} non-empty blocks, {tuple_count} entries")

    rendered.extend(["endsm", ""])
    OUT_FILE.write_text("\n".join(rendered), encoding="utf-8")
    for summary in summaries:
        print(summary)
    print(f"wrote {OUT_FILE.relative_to(RQ5_DIR.parent.parent.parent)}")


if __name__ == "__main__":
    main()
